Update BuildVexMobile.yml

diff --git a/.github/workflows/BuildVexMobile.yml b/.github/workflows/BuildVexMobile.yml
--- a/.github/workflows/BuildVexMobile.yml
+++ b/.github/workflows/BuildVexMobile.yml
@@ -6,68 +6,78 @@ on:
       - main
 
 jobs:
-  build:
+  setup-capacitor-environment:
     runs-on: ubuntu-latest
-    timeout-minutes: 15 # Aumentei o timeout para 15 minutos para dar tempo suficiente para a instalação das dependências
 
     steps:
-      - name: Checkout
-        uses: actions/checkout@v2.3.4
+      - name: Check out code
+        uses: actions/checkout@v2
 
-      - name: Install Node
-        uses: actions/setup-node@v3
+      - name: Set up Node.js environment
+        uses: actions/setup-node@v2
         with:
-          node-version: '14' # Versão do Node que deseja instalar
-          cache: npm
+          node-version: 16
 
-      - name: Install Java
-        uses: actions/setup-java@v1
+      - name: Install dependencies and initialize Capacitor
+        run: |
+          npm install
+          npx cap init android
+
+      - name: Install Java JDK
+        uses: actions/setup-java@v2
         with:
-          java-version: '17' # Versão do Java que deseja instalar
+          distribution: 'adopt'
+          java-version: '17'
+
+      - name: Print Java version
+        run: java -version
 
       - name: Install Gradle
         uses: gradle/gradle-build-action@v2
         with:
-          gradle-version: '7.6' # Versão do Gradle que deseja instalar
+          gradle-version: 7.3
 
-      - name: Install Capacitor and Add Android Platform
+      - name: Decode keystore from Base64
         run: |
-          npm install -g @capacitor/cli
-          npm install
-          npx cap update
-          npx cap add android
+          echo "${{ secrets.COOKIE_KEY }}" | base64 --decode > $HOME/release.keystore
+
+      - name: Find debug keystore
+        run: |
+          debug_keystore_path="$HOME/release.keystore"
+          if [ -f "$debug_keystore_path" ]; then
+            echo "Debug Keystore: $debug_keystore_path"
+          else
+            echo "Debug Keystore not found."
+            exit 1
+          fi
 
       - name: Give execute permission to gradlew
         run: chmod +x ./android/gradlew
-        
+
+      - name: Build the React application
+        run: npm run build
+
+      - name: Sync files with Capacitor
+        run: npx cap sync
+
+      - name: Verify Capacitor platform
+        run: npx cap ls
+
       - name: Install apksigner
         run: sudo apt update && sudo apt install -y apksigner
 
-      - name: Install NPM Dependencies
-        run: npm ci
-
-      - name: Decode keystore
+      - name: Build Android APK
         run: |
-          mkdir -p ./android/keystore/
-          echo "${{ secrets.COOKIE_KEY }}" | base64 -d > ./android/keystore/release.keystore
-        
-      - name: Build APK
-        run: |
-          npx cap build android --keystorepath "keystore/release.keystore" --keystorepass $KEYSTOREPASS --keystorealiaspass $KEYSTOREALIASPASS --keystorealias $KEYSTOREALIAS --androidreleasetype APK
-          rm -rf ./android/keystore/release.keystore
-          mv ./android/app/build/outputs/apk/release/app-release-signed.apk ./android/app/build/outputs/apk/release/SEGES+.apk
-          rm -rf ./android/app/build/outputs/apk/release/app-release-unsigned.apk
-
-        env:
-          KEYSTOREPASS: cookieukw
-          KEYSTOREALIASPASS: cookieukw
-          KEYSTOREALIAS: cookieukw
+          npx cap build android --release
+          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $HOME/release.keystore -storepass ${{ secrets.KEYSTORE_PASSWORD }} ${{ github.workspace }}/android/app/build/outputs/apk/release/app-release.apk ${{ secrets.KEYSTORE_ALIAS }}
+          ${{ github.workspace }}/android/app/build/outputs/apk/release/app-release.apk
 
       - name: Create draft release
         uses: softprops/action-gh-release@v1
         with:
           draft: true
           files: |
-            ./android/app/build/outputs/apk/release/*.apk
+            ${{ github.workspace }}/android/app/build/outputs/bundle/release/*.aab
+            ${{ github.workspace }}/android/app/build/outputs/apk/release/*.apk
         env:
-          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
+          GITHUB_TOKEN: ${{ secrets.VEX_TOKEN }}
